[bot]
packs = [
    'VampireQueen',
    'MrPanda',
    'akiovk',
    'Degrodpack',
    'TrashBY',
    'xyligan'
]
options = 3

[messages]
start = '''Бот для адпраўкі выпадковых стыкераў. Ўвядзіце /help для атрымання спісу каманд.
Папярэджанне! Аўтар не ведае беларускай мовы. Калі вы знойдзеце памылкі, калі ласка звяжыцеся з аўтарам.
@istimaldar istimaldar@gmail.com
Або стварыце иш'ю / PR ў рэпазіторыі праекта.'''
help = '''Бот для адпраўкі выпадковых стыкераў.
Бот выкарыстоўваецца ў інлайн рэжыме. Каб адправіць выпадковы стыкер, напішыце @rndstsnd ў патрэбным дыялогу.
Спіс каманд у звычайным рэжыме:
/start - Выводзіць базавую інфармацыю аб боце
/help - Выводзіць інфармацыю аб выкарыстанні бота
/privacy - Паказвае палітыку прыватнасці'''
privacy = '''Бот не выкарыстоўвае і не захоўвае ніякіх дадзеных юзэра.'''
unknown = '''Невядомая каманда.
Ўвядзіце /help для атрымання спісу каманд.'''
